# Generated by Django 5.2 on 2025-04-05 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('greeting', 'Greeting')], max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('count', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'date'], name='api_useract_user_id_7e35c9_idx'),
        ),
    ]
