# Generated by Django 5.2 on 2025-04-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_useractivity_delete_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SustainableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('clothing', 'Sustainable Clothing'), ('home', 'Eco-Friendly Home Goods'), ('electronics', 'Recycled Electronics'), ('packaging', 'Sustainable Packaging'), ('furniture', 'Upcycled Furniture'), ('accessories', 'Green Accessories'), ('other', 'Other')], max_length=50)),
            ],
        ),
    ]
