# Generated by Django 5.2 on 2025-04-05 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_requests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SustainableItem',
        ),
    ]
